In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import urllib.request
import datetime as dt     
from geopy.geocoders import Nominatim

pd.set_option('display.max_columns', None)
import plotly as py
import cufflinks as cf
%matplotlib inline

In [2]:
start_date = "20120101"
print(start_date)

20120101


In [3]:
end_date = dt.datetime.today().strftime("%Y%m%d")
print(end_date)

20221116


In [4]:
address = input("Enter City Name:")

Enter City Name:Guwahati


In [5]:
geolocator = Nominatim(user_agent="Aman")
location = geolocator.geocode(address)
print(location.address)
print((location.latitude, location.longitude))
latitude = location.latitude
longitude = location.longitude

Guwahati, Kamrup Metropolitan, Assam, 781015, India
(26.1805978, 91.753943)


In [6]:
url = 'https://power.larc.nasa.gov//api/temporal/daily/point?parameters=T2M_MAX,T2M_MIN,RH2M,PRECTOTCORR,PS,WS10M_RANGE&community=SB&longitude={}6&latitude={}&start={}&end={}&format=CSV'.format(longitude,latitude,start_date,end_date)

In [7]:
urllib.request.urlretrieve(url,'weather.csv')

('weather.csv', <http.client.HTTPMessage at 0x148a62440>)

In [39]:
df = pd.read_csv('weather.csv',skiprows=14)

In [40]:
df.head()

YEAR  MO  DY  T2M_MAX  T2M_MIN   RH2M  PRECTOTCORR     PS  WS10M_RANGE
0  2012   1   1    23.43     9.09  72.50         0.08  96.90         1.93
1  2012   1   2    21.87    11.00  82.31         6.35  96.82         2.31
2  2012   1   3    22.73     9.69  84.69         0.68  96.74         2.26
3  2012   1   4    21.19     9.00  83.12         0.00  96.86         1.99
4  2012   1   5    21.58     9.29  78.38         0.00  97.01         2.02

In [41]:
df['YEAR'] = df.YEAR.astype(str)
df['MO'] = df.MO.astype(str)
df['DY'] = df.DY.astype(str)

df['DATE'] = df['YEAR'].str.cat(df['MO'], sep = '/').str.cat(df['DY'], sep = '/')
df.head()

YEAR MO DY  T2M_MAX  T2M_MIN   RH2M  PRECTOTCORR     PS  WS10M_RANGE  \
0  2012  1  1    23.43     9.09  72.50         0.08  96.90         1.93   
1  2012  1  2    21.87    11.00  82.31         6.35  96.82         2.31   
2  2012  1  3    22.73     9.69  84.69         0.68  96.74         2.26   
3  2012  1  4    21.19     9.00  83.12         0.00  96.86         1.99   
4  2012  1  5    21.58     9.29  78.38         0.00  97.01         2.02   

       DATE  
0  2012/1/1  
1  2012/1/2  
2  2012/1/3  
3  2012/1/4  
4  2012/1/5

In [42]:
df.drop(columns=['YEAR','MO','DY'],axis=1,inplace=True)
df.head()

T2M_MAX  T2M_MIN   RH2M  PRECTOTCORR     PS  WS10M_RANGE      DATE
0    23.43     9.09  72.50         0.08  96.90         1.93  2012/1/1
1    21.87    11.00  82.31         6.35  96.82         2.31  2012/1/2
2    22.73     9.69  84.69         0.68  96.74         2.26  2012/1/3
3    21.19     9.00  83.12         0.00  96.86         1.99  2012/1/4
4    21.58     9.29  78.38         0.00  97.01         2.02  2012/1/5

In [43]:
df.set_index(['DATE'], inplace = True)
df.head()

T2M_MAX  T2M_MIN   RH2M  PRECTOTCORR     PS  WS10M_RANGE
DATE                                                              
2012/1/1    23.43     9.09  72.50         0.08  96.90         1.93
2012/1/2    21.87    11.00  82.31         6.35  96.82         2.31
2012/1/3    22.73     9.69  84.69         0.68  96.74         2.26
2012/1/4    21.19     9.00  83.12         0.00  96.86         1.99
2012/1/5    21.58     9.29  78.38         0.00  97.01         2.02

In [44]:
df.dtypes

T2M_MAX        float64
T2M_MIN        float64
RH2M           float64
PRECTOTCORR    float64
PS             float64
WS10M_RANGE    float64
dtype: object

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3972 entries, 2012/1/1 to 2022/11/15
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   T2M_MAX      3972 non-null   float64
 1   T2M_MIN      3972 non-null   float64
 2   RH2M         3972 non-null   float64
 3   PRECTOTCORR  3972 non-null   float64
 4   PS           3972 non-null   float64
 5   WS10M_RANGE  3972 non-null   float64
dtypes: float64(6)
memory usage: 217.2+ KB


In [46]:
with pd.option_context('display.max_rows', None,'display.max_columns', None,'display.precision', 3):
    print(df)

            T2M_MAX  T2M_MIN    RH2M  PRECTOTCORR      PS  WS10M_RANGE
DATE                                                                  
2012/1/1      23.43     9.09   72.50         0.08   96.90         1.93
2012/1/2      21.87    11.00   82.31         6.35   96.82         2.31
2012/1/3      22.73     9.69   84.69         0.68   96.74         2.26
2012/1/4      21.19     9.00   83.12         0.00   96.86         1.99
2012/1/5      21.58     9.29   78.38         0.00   97.01         2.02
2012/1/6      21.38     8.72   81.88         0.00   97.12         1.70
2012/1/7      22.24     8.87   81.81         0.00   97.23         1.14
2012/1/8      22.02     8.80   81.31         0.15   97.23         1.34
2012/1/9      21.86    10.10   82.50         0.38   97.09         2.10
2012/1/10     23.40    10.45   76.81         0.12   96.98         2.19
2012/1/11     22.20     9.69   77.88         0.14   96.99         1.51
2012/1/12     22.01     8.12   81.69         0.00   96.86         1.47
2012/1

In [47]:
df.shape

(3972, 6)

In [48]:
df.isnull().any()

T2M_MAX        False
T2M_MIN        False
RH2M           False
PRECTOTCORR    False
PS             False
WS10M_RANGE    False
dtype: bool

In [49]:
df.tail()

T2M_MAX  T2M_MIN    RH2M  PRECTOTCORR      PS  WS10M_RANGE
DATE                                                                  
2022/11/11    27.00    16.74   75.81         1.71   96.85         1.12
2022/11/12    26.35    16.19   75.12         0.53   96.81         1.32
2022/11/13  -999.00  -999.00 -999.00      -999.00 -999.00      -999.00
2022/11/14  -999.00  -999.00 -999.00      -999.00 -999.00      -999.00
2022/11/15  -999.00  -999.00 -999.00      -999.00 -999.00      -999.00

In [50]:
df.describe()
import sklearn as sk

In [51]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)
print('Scaled df:\n', df_scaled, '\n', df_scaled.shape)

Scaled df:
 [[0.98454472 0.9831859  0.97943327 0.88534817 0.99954396 0.99680323]
 [0.98304252 0.98504872 0.98840037 0.89090442 0.999471   0.99718167]
 [0.98387066 0.98377108 0.99057587 0.88587987 0.99939803 0.99713187]
 ...
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]] 
 (3972, 6)


In [52]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df_scaled, test_size = 0.2, shuffle = False)

# X - Y
x_train, y_train, x_test, y_test = [], [], [], []
for i in range (1, len(train)):
    x_train.append(train[i-1])
    y_train.append(train[i])
for i in range (1, len(test)):
    x_test.append(test[i-1])
    y_test.append(test[i])


In [53]:
pd.DataFrame(x_train)

0         1         2         3         4         5
0     0.984545  0.983186  0.979433  0.885348  0.999544  0.996803
1     0.983043  0.985049  0.988400  0.890904  0.999471  0.997182
2     0.983871  0.983771  0.990576  0.885880  0.999398  0.997132
3     0.982388  0.983098  0.989141  0.885277  0.999507  0.996863
4     0.982763  0.983381  0.984808  0.885277  0.999644  0.996893
...        ...       ...       ...       ...       ...       ...
3171  0.992296  0.997845  0.993547  0.898313  0.998677  0.996524
3172  0.992364  0.997123  0.992176  0.896195  0.998760  0.996604
3173  0.989764  0.997737  0.995777  0.894520  0.998796  0.995917
3174  0.991006  0.997776  0.994004  0.893572  0.998796  0.996036
3175  0.994357  0.997757  0.988172  0.890293  0.998541  0.996385

[3176 rows x 6 columns]

In [54]:
pd.DataFrame(y_train)

0         1         2         3         4         5
0     0.983043  0.985049  0.988400  0.890904  0.999471  0.997182
1     0.983871  0.983771  0.990576  0.885880  0.999398  0.997132
2     0.982388  0.983098  0.989141  0.885277  0.999507  0.996863
3     0.982763  0.983381  0.984808  0.885277  0.999644  0.996893
4     0.982571  0.982825  0.988007  0.885277  0.999745  0.996574
...        ...       ...       ...       ...       ...       ...
3171  0.992364  0.997123  0.992176  0.896195  0.998760  0.996604
3172  0.989764  0.997737  0.995777  0.894520  0.998796  0.995917
3173  0.991006  0.997776  0.994004  0.893572  0.998796  0.996036
3174  0.994357  0.997757  0.988172  0.890293  0.998541  0.996385
3175  0.992364  0.997952  0.993492  0.894768  0.998659  0.995997

[3176 rows x 6 columns]

In [55]:
x_train, y_train = np.array(x_train), np.array(y_train)
x_test, y_test = np.array(x_test), np.array(y_test)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((3176, 6), (3176, 6), (794, 6), (794, 6))

In [56]:
import numpy as np
import pandas as pd