In [1]:
import random
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
import pandas as pd
from numpy import savetxt, loadtxt
from datetime import date
from matplotlib import cm

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = b * 5
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [4]:
a = np.arange(10, 51, 2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [5]:
a = [[random.random() for _ in range(10)] for _ in range(10)]
print(a)
savetxt('lab1.txt', a)
b = loadtxt('lab1.txt')
print(b)

[[0.19929570759273418, 0.5001943051493838, 0.5907874159504238, 0.34385051883983186, 0.27074760894014216, 0.5390664165108358, 0.588029183750363, 0.4859042229507976, 0.1553356243981393, 0.20709582117788905], [0.3103006884243068, 0.6513411007321303, 0.5542430277661363, 0.04739959397853888, 0.16553674289862264, 0.5246568065213519, 0.812044180314648, 0.8072536544873814, 0.1496473917419998, 0.4817848239043505], [0.7386394038123554, 0.034472436520810446, 0.4171469222053391, 0.592920541067895, 0.2228294682110189, 0.33502326522818515, 0.8602332152766974, 0.798936521815833, 0.366703568245092, 0.40768966569107445], [0.045373367198962344, 0.39360802570912334, 0.2830704714908525, 0.1908003547683832, 0.1962989339440966, 0.03235220301781816, 0.9988391813481731, 0.5839596131017141, 0.5252953410284411, 0.31473759859406514], [0.2026244065679662, 0.75716088379022, 0.12309556419593037, 0.3443265097259156, 0.8670892528870016, 0.9150455586857571, 0.9366289606866965, 0.3096774054380078, 0.5949027646664472, 0

In [6]:
a = Image.open('image.jpg')
b = np.asarray(a)
c = b.reshape(3, -1)
pd.DataFrame(c).to_csv('LAb1.csv')

In [14]:
x = pd.read_csv('df1')
x = x.to_numpy()
x = np.delete(x,-1,axis=0)
x = np.delete(x,-1,axis=1)
print(x)

[['2000-01-01' 1.339091086710764 -0.1636430589256459 -0.6464425533392314]
 ['2000-01-02' -0.7749840885611867 0.1370343640539491 -0.8827159154980816]
 ['2000-01-03' -0.9210371677204512 -0.4829432213842944
  -0.4170996442808702]
 ...
 ['2002-09-23' -0.642658867032067 -0.1047251878607459 -0.6318289284439236]
 ['2002-09-24' 0.3701357432455675 0.2332185087940045 0.5358967567312249]
 ['2002-09-25' 0.1833389955742047 1.2857832745036837 -1.052593011992047]]


In [8]:
d = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print(d)

2022-08-12 00:00:00


In [12]:
def problem3(birth_date):
    a = (date.today()-birth_date).days
    b = int(a / 365.25)
    print(b)

problem3(date(1999,10,20))

22
